name: WholeBrain
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - certifi=2019.3.9=py36_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2019.3=203
  - mkl=2019.3=203
  - mkl_fft=1.0.10=py36h14836fe_0
  - mkl_random=1.0.2=py36h343c172_0
  - numpy=1.16.2=py36h19fb1c0_0
  - numpy-base=1.16.2=py36hc3f5095_0
  - pip=19.0.3=py36_0
  - python=3.6.8=h9f7ef89_7
  - scipy=1.2.1=py36h29ff71c_0
  - setuptools=41.0.0=py36_0
  - sqlite=3.27.2=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.33.1=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
prefix: C:\Users\dagus\.conda\envs\WholeBrain

